# Generated by Django 5.1.11 on 2025-08-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('worker', 'Worker')], max_length=20, null=True, verbose_name='Role'),
        ),
    ]
