# Generated by Django 5.1.11 on 2025-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('other', 'Other')], max_length=20, null=True, verbose_name='Specialty'),
        ),
    ]
