# Generated by Django 5.1.11 on 2025-08-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('received', 'Received'), ('completed', 'Completed'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='created', max_length=20),
        ),
    ]
