# Generated by Django 5.1.11 on 2025-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_system',
            field=models.CharField(blank=True, choices=[('click', 'Click'), ('payme', 'Payme')], max_length=20, null=True),
        ),
    ]
