# Generated by Django 5.1.11 on 2025-08-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='specialty',
            field=models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('manager', 'Manager'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
